server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/products
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
